# Sample EPP configuration for running with KvCache and load aware scorers
#
apiVersion: inference.networking.x-k8s.io/v1alpha1
kind: EndpointPickerConfig
plugins:
- type: single-profile-handler
- type: decode-filter
- type: prefix-cache-scorer
  parameters:
    mode: cache_tracking
    kvCacheRedisAddr: ${REDIS_HOST}:${REDIS_PORT}
- type: load-aware-scorer
- type: max-score-picker
schedulingProfiles:
- name: default
  plugins:
  - pluginRef: decode-filter
  - pluginRef: prefix-cache-scorer
    weight: 2.0
  - pluginRef: load-aware-scorer
    weight: 1.0
  - pluginRef: max-score-picker
